name: Update version file

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get-tag
        run: |
          echo "LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

      - name: Update version.json
        run: |
          echo "{
            \"version\": \"${{steps.get-tag.outputs.LATEST_TAG}}\"
          }" > version.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update version to ${{steps.get-tag.outputs.LATEST_TAG}}"
